sudo: false
language: ruby
rvm: 
  - 2.2.0
services:
  - redis-server
addons:
  apt:
    packages:
      - libicu-dev
env: COVERALLS=1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
cache: bundler
bundler_args:
  - "--without development --deployment --jobs=3 --retry=3"
before_script:
  - "bundle exec rake foodsoft:setup:stock_config"
  - 'printf "test: &test\n  adapter: mysql2\n  database: foodsoft_test\n  username: travis\n  encoding: utf8\n" >config/database.yml'
  - 'printf "sharedlists:\n  <<: *test\n" >>config/database.yml'
  - "echo \"SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));\" | mysql"
  - 'bundle exec rake db:create db:schema:load RAILS_ENV=test'
script: bundle exec rake rspec-rerun:spec
